$content-type:text/x-suikawiki
$hash:c5489169fcd03e33250da0b4d08aa54d
$modified:1784721977
%name:「私年号」の呼称と分類
%name:一字異音の年号
%name:一字異音年号
%name:同音異字の年号
%name:同音異字の異年号
%name:同音異字年号
%name:日本偽年号
%name:異号
%name:私号
%name:私年号の呼称と分類
%name:私年号的諸資料
%name:行仮借年号
%name:逸号
%name:音仮借年号
$parent:私年号
$title:「私年号」の呼称と分類
$title-type:text/plain
