$content-type:text/x-suikawiki
$hash:8338f5d68185bf191435159910df9183
$modified:1784961700
%name:エフン
%name:シャウチ
%name:一多理
%name:以仁王落人伝説
%name:北原巻物
%name:北原氏巻物
%name:多理
%name:永知
%name:自正
%name:自正吉
%name:自正吉元年
%name:高倉宮以仁王御墓考
%name:高倉宮以仁王御墳墓考
%name:高倉宮御墓考
%name:高橋巻物
%name:高橋氏巻物
$parent:以仁王
$title:以仁王落人伝説
$title-type:text/plain
