$content-type:text/x-suikawiki
$hash:9f3f456ab996081597eeb566fb69396e
$modified:1783069865
%name:あめたもつ
%name:うけやすき
%name:人のやすけき
%name:人のやすけき年
%name:元号訓読
%name:和語元号名
%name:和語紀年
%name:天ただしき
%name:天たゞしき
%name:寛尓永志
%name:寛尓永志登云祁流歳
%name:寛爾永志
%name:寛爾永志登云祁流歲
%name:文あきらけき
%name:文あきらけき年
$parent:元号名
$title:和語元号名
$title-type:text/plain
