$content-type:text/x-suikawiki
$hash:a5dfa5c3be9da7b4b22eb1e4a806b9c0
$modified:1783999568
%name:C.C.
%name:C.E.
%name:CC
%name:CE
%name:Correct Century
%name:Cosmic Era
%name:P.D.
%name:PD
%name:Post Disaster
%name:R.C.
%name:RC
%name:Regild Century
%name:ガンダムの日時
%name:コズミック・イラ
%name:リギルド・センチュリー
%name:宇宙世紀
%name:正歴
$parent:架空の日時
$title:ガンダムの日時
$title-type:text/plain
