$content-type:text/x-suikawiki
$hash:cfcdd0a03ca39cdcc1c95b11b69f9cd5
$modified:1784128309
%name:てんぽ
%name:てんぽう
%name:てんぽう元年
%name:てんぽう元年薬缶の年
%name:てんぽ元年
%name:やかんの年
%name:天保元年やかんの年
%name:女文
%name:徳保
%name:日本前近代文芸の元号
%name:日本前近代文芸の日時
%name:日本前近代芸能の元号
%name:烏鵲
%name:烏鷺
$parent:作中元号
$title:日本前近代文芸の元号
$title-type:text/plain
