$content-type:text/x-suikawiki
$hash:d7ac605c7e895388ad6c554cf0fca9df
$modified:1784689405
%name:てんぽ
%name:てんぽう
%name:てんぽう元年
%name:てんぽう元年薬缶の年
%name:てんぽ元年
%name:やかんの年
%name:天保元年やかんの年
%name:女文
%name:徳保
%name:日本前近代文芸の元号
%name:日本前近代文芸の日時
%name:日本前近代芸能の元号
%name:日本前近代芸能の日時
%name:烏鵲
%name:烏鷺
$parent:作中元号
$title:日本前近代文芸の元号
$title-type:text/plain
