$content-type:text/x-suikawiki
$hash:3a71712c7831e569c04254987e329be3
$modified:1791689018
%name:<BIG2>
%name:<FLEX>
%name:<PHON>
%name:<RED>
%name:<big2>
%name:<flex>
%name:<phon>
%name:<red>
%name:BIG2
%name:FLEX
%name:PHON
%name:RED
%name:big2
%name:flex
%name:phon
%name:red
$title:phon, big2, sub2, red, blue, flex, idiv, requ, cen, fleft, fright, floatl, floatr, nbr 要素 (HTML)
$title-type:text/plain
