$content-type:text/x-suikawiki
$hash:99063f67e3fa8bf917fcdb9f696699ba
$modified:1788828638
%name:Accept
%name:Accept:
%name:Accept:欄
%name:Accept:領域
%name:Accept:頭欄
%name:HTTP_ACCEPT
%name:accept
%name:accept-ext
%name:accept-params
$parent:HTTPヘッダー
$title:Accept: ヘッダー (HTTP)
$title-type:text/plain
