$content-type:text/x-suikawiki
$hash:c8b3437d345b6b94d27ece1a60c7e107
$modified:1785163100
%name:みろく
%name:みろく元年
%name:ミクニ
%name:ミクニ元年
%name:ミロク
%name:ミロク元年
%name:令和(レムリア)
%name:令和(レムリア)元年
%name:弥勒
%name:弥勒 (スピ)
%name:弥勒 (スピ系)
%name:弥勒 (空の真法)
%name:弥勒元年
%name:彌勒
%name:彌勒元年
%name:神紀
%name:神紀元年
$parent:日本の私年号
$title:弥勒 (スピ系)
$title-type:text/plain
