$content-type:text/x-suikawiki
$hash:74ffeca0d1090d779dea9c2d01837b4f
$modified:1788079787
%name:4文字元号の省略形
%name:4文字元号名の省略形
%name:云
%name:元号略号
%name:减寶
%name:勝〓⿱穴奴
%name:勝宝
%name:四字元号の省略
%name:天〓⿱穴奴
%name:天平宝
%name:天平宝字
%name:天平感
%name:天感
%name:字
%name:感宝
%name:景雲
%name:神護
$parent:元号名
$title:元号略号
$title-type:text/plain
