$content-type:text/x-suikawiki
$hash:dd2aaccf5871a79ac2094c590462cc0b
$modified:1787908445
%name:EUDC
%name:UDC
%name:User-Defined Characters
%name:end-user defined character
%name:end-user defined characters
%name:user-defined character
%name:user-defined characters
%name:ユーザー使用領域
%name:石巻市Unicode外字
$parent:外字
$title:EUDC
$title-type:text/plain
