$content-type:text/x-suikawiki
$hash:b6b946ffa884afdf3bfb69681c70d99f
$modified:1791042112
%name:EUDC
%name:UDC
%name:User-Defined Characters
%name:end-user defined character
%name:end-user defined characters
%name:user-defined character
%name:user-defined characters
%name:ユーザー使用領域
%name:石巻市Unicode外字
$parent:外字
$title:EUDC
$title-type:text/plain
