$content-type:text/x-suikawiki
$hash:051d24d4b0927848f90c76126a80defa
$modified:1790645768
%name:Noto Sans CJK
%name:SHS
%name:Source Han
%name:Source Han Sans
%name:Source Han Serif
%name:shs
%name:三式明朝
%name:原ノ味フォント
%name:原ノ味明朝
%name:原ノ味角ゴシック
%name:源ノ明朝
%name:源ノ角ゴシック
%name:霧明朝
$parent:フォント
$title:Source Han
$title-type:text/plain
