$content-type:text/x-suikawiki
$hash:721fcb4bc8e2c9ac9f4c1dc847a65a02
$modified:1790825324
%name:Permission
%name:Permission API
%name:Permissions
%name:Permissions API
%name:PushPermissionState
%name:The Permissions API
%name:denied
%name:express permission
%name:granted
%name:permission
%name:permission manager
%name:permissionState
%name:prompt
%name:push permission status
%name:承認の要求
%name:許可
$parent:Webプラットフォーム
$title:
$title-type:text/plain
