$content-type:text/x-suikawiki
$hash:0603d5755df81a7a951b806b081939f5
$modified:1784373402
%name:@N
%name:@U
%name:CLCR
%name:ConLang Code Registry
%name:EM
%name:NU
%name:US
%name:Unicode base language code
%name:ZXX
%name:base language code
%name:language
%name:language subtag
%name:long code
%name:mis
%name:primary language subtag
%name:skf言語
%name:und
%name:unicode_language_subtag
%name:zxx
%name:zxx-x-iat
%name:一次言語部分タグ
%name:名前付け規則言語コード
%name:基底言語符号
%name:言語
%name:言語部分タグ
%name:長符号
$node_id:8019.36882960452
$parent:言語タグ
$title:言語部分タグ (一次言語部分タグ)
$title-type:text/plain
