$content-type:text/x-suikawiki
$hash:df2fbea3248a0c2118683b2f89adeece
$modified:1784178009
%name:ICU transform rule language
%name:LDML Transforms
%name:RuleBasedTransliterator
%name:Transform Rule
%name:Transforms
%name:Transliteration Rules
%name:Unicode's Transliteration Rules
%name:transform rule
$parent:ICU
$title:Transform Rule
$title-type:text/plain
