$content-type:text/x-suikawiki
$converted-from-sw3:1235100381
$hash:0e2e42ff364097a5e74c0aad2445a144
$modified:1784177580
%name:LDML
%name:Locale Data Markup Language
%name:UTS #35
%name:UTS #35: Unicode Locale Data Markup Language
$node_id:7981.03204067217
$parent:Unicode
$sw3-key:4C444D4C
$title:LDML
$title-type:text/plain
