$content-type:text/x-suikawiki
$converted-from-sw3:1235100381
$hash:99f18045eed0703128368f89ceaeb39f
$modified:1784183331
%name:LDML
%name:Locale Data Markup Language
%name:UTS #35
%name:UTS #35: Unicode Locale Data Markup Language
$node_id:7981.03204067217
$parent:Unicode
$sw3-key:4C444D4C
$title:LDML
$title-type:text/plain
