$content-type:text/x-suikawiki
$hash:a280c904736cdb8f9e9a841521973513
$historical:1
$modified:1785899061
%name:<DjVuXML>
%name:DjVu
%name:DjVu XML
%name:DjVuXML
%name:DjVuブラウザプラグイン
%name:djvu
%name:image/djvu
%name:image/vnd.djvu
%name:image/x-djvu
%name:image/x.djvu
$parent:画像形式
$title:DjVu
$title-type:text/plain
