$content-type:text/x-suikawiki
$hash:a43a1cd708b5b6c8c24497e70e6ef628
$modified:1783076816
%name:「はるくさ」木簡
%name:はるくさ
%name:はるくさの
%name:はるくさの はじめのとし
%name:はるくさのはじめしとし
%name:はるくさのはじめのとし
%name:はるくさ木簡
%name:春草
%name:春草のはじめのとし
%name:春草のはじめの年
%name:治民
%name:治民元年
%name:皮留久佐乃皮斯米之刀斯
$parent:万葉仮名
$title:皮留久佐乃皮斯米之刀斯
$title-type:text/plain
