$content-type:text/x-suikawiki
$hash:dd7baae3258ec2bb2a5ca5dba7026abb
$modified:1786800538
%name:ミロク私年号
%name:一茶が残した 謎󠄀の年号『美禄』考
%name:一茶が残した謎󠄀の年号『美禄』考
%name:勒彌
%name:弥勒
%name:弥勒元年
%name:弥勒私年号
%name:弥禄
%name:弥靱󠄁
%name:彌勒
%name:旅勒
%name:私年号命禄の年代に就いて
%name:私年󠄂號命祿の年󠄂代に就いて
%name:美禄
%name:𣃥勒
%name:𫟈禄
$parent:日本の私年号
$title:弥勒 (元号)
$title-type:text/plain
